{
	"version": 1687400399,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sky-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tile.png",
		"images/hero-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/drone-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite8-sheet2.png",
		"images/trigger-sheet0.png",
		"images/trigger-sheet1.png",
		"images/trigger-sheet2.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/flag-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/title-sheet0.png",
		"images/playbtn-sheet0.png",
		"images/restart_btn-sheet0.png",
		"images/menu_btn-sheet0.png",
		"images/jump-sheet0.png",
		"images/left_key-sheet0.png",
		"images/right_key-sheet0.png",
		"media/you_re in the future.ogg",
		"media/footstepsconcrete2.ogg",
		"media/jump.ogg",
		"media/item_appears.ogg",
		"media/sweet treats.ogg",
		"media/level up 2 (miniclip).ogg",
		"media/gameover.ogg",
		"media/victory.ogg",
		"media/groovy booty.ogg",
		"media/groovy saturday.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}